ProyectoArduino: SensorBase Class Reference
SensorBase Class Reference abstract
Clase abstracta base que define la interfaz común para todos los tipos de sensores.
#include <SensorBase.h>
Public Member Functions
SensorBase (const char *nom)
Constructor de la clase base.
virtual void imprimirInfo () const =0
Método virtual puro para imprimir la información específica del sensor.
virtual void procesarLectura ()=0
Método virtual puro para iniciar el proceso de lectura y manejo de datos del sensor.
const char * obtenerNombre () const
Obtiene el nombre del sensor.
virtual ~SensorBase ()
Destructor virtual.
Static Public Attributes
static ListaSensor< SensorBase * > sensoresRegistrados
Lista estática para registrar todos los sensores creados en el sistema.
Protected Attributes
char nombre [50]
Nombre descriptivo del sensor.
Detailed Description
Clase abstracta base que define la interfaz común para todos los tipos de sensores.
Esta clase implementa un mecanismo para registrar automáticamente cada instancia de sensor creado en una lista estática, facilitando la gestión polimórfica.
Definition at line 18 of file SensorBase.h.
Constructor & Destructor Documentation
SensorBase()
SensorBase::SensorBase (const char * nom) inline
Constructor de la clase base.
Inicializa el nombre del sensor y lo registra automáticamente en la lista estática sensoresRegistrados.
Parameters
nom Cadena de caracteres con el nombre del sensor (máximo 49 caracteres).
Definition at line 35 of file SensorBase.h.
References ListaSensor< T >::agregar(), nombre, and sensoresRegistrados.
~SensorBase()
virtual SensorBase::~SensorBase () inline virtual
Destructor virtual.
Es importante que sea virtual para asegurar que el destructor correcto de la clase derivada sea llamado cuando se elimina un objeto SensorBase a través de un puntero base (polimorfismo).
Definition at line 66 of file SensorBase.h.
Member Function Documentation
imprimirInfo()
virtual void SensorBase::imprimirInfo () const pure virtual
Método virtual puro para imprimir la información específica del sensor.
Debe ser implementado por todas las clases derivadas.
Implemented in SensorPresion, and SensorTemperatura.
Referenced by ListaGeneral::imprimirTodos(), and main().
obtenerNombre()
const char * SensorBase::obtenerNombre () const inline
Obtiene el nombre del sensor.
Returns
Puntero constante a la cadena de caracteres que contiene el nombre del sensor.
Definition at line 57 of file SensorBase.h.
References nombre.
Referenced by ListaGeneral::agregar(), ListaGeneral::buscar(), ListaGeneral::procesarTodos(), and ListaGeneral::~ListaGeneral().
procesarLectura()
virtual void SensorBase::procesarLectura () pure virtual
Método virtual puro para iniciar el proceso de lectura y manejo de datos del sensor.
Debe ser implementado por todas las clases derivadas para definir su lógica de procesamiento.
Implemented in SensorPresion, and SensorTemperatura.
Referenced by ListaGeneral::procesarTodos().
Member Data Documentation
nombre
char SensorBase::nombre[50] protected
Nombre descriptivo del sensor.
Definition at line 20 of file SensorBase.h.
Referenced by obtenerNombre(), SensorTemperatura::procesarLectura(), SensorBase(), SensorPresion::~SensorPresion(), and SensorTemperatura::~SensorTemperatura().
sensoresRegistrados
ListaSensor< SensorBase * > SensorBase::sensoresRegistrados static
Lista estática para registrar todos los sensores creados en el sistema.
para operaciones polimórficas (como el procesamiento masivo).
Utiliza ListaSensor<SensorBase*> para almacenar punteros de clase base.
Definition at line 28 of file SensorBase.h.
Referenced by SensorBase().
The documentation for this class was generated from the following files:
include/SensorBase.h
src/SensorBase.cpp